### ISSUE TITLE
E2E PoC

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/XCQ#2]
A feasibility E2E PoC to ensure we can do what we want to do.

- Example XCQ Program
  - A XCQ program to query balances of some accounts and return the sum
  - Use query host call to invoke fungibles extension to fetch balance
  - Return primitive types
- XCQ VM
  - Uses PolkaVM
  - Input:
    - A XCQ program
    - A fungibles extension data provider
- Demo runtime
  - Implements XCQ runtime API
- Demo SDK
  - Allow submission of XCQ program and invoke it
  - Includes the example XCQ program

This only covers the offchain part. The onchain XCQ execution via XCM is out of scope for this PoC.

**Comment by indirection42** [comment]
I still get confused about how to connect the executor to pallet balances.  Please give me some suggestions.
1. We impl our Runtime via 2 ways: first, we configure some useful pallets with `derive_impl` using `DefaultConfig`s, then we configure additional apis via `impl_runtime_apis`. Is my understanding right?
2. So far as I know, `pallet_balance`' s AccountStore is specified as `System` which is `frame_system`. The question is what I supposed to get the total balance of an account is accessing `system::AccountInfo` via `frame_system`'s [account(who)](https://paritytech.github.io/polkadot-sdk/master/frame_system/pallet/struct.Pallet.html#method.account) dispatchable or invoke pallet_balance's dispatchables [free_balance(who)](https://docs.rs/pallet-balances/latest/pallet_balances/pallet/struct.Pallet.html#method.free_balance)+[reserved_balance(who)](https://docs.rs/pallet-balances/latest/pallet_balances/pallet/struct.Pallet.html#method.reserved_balance)?
3. Specifically, `accounts` to be queried will be given via `XcqApi_execute_query`'s `input`, and `polkavm program` is supposed to do nothing but several host_calls via `pallet_balance` or `frame_system` apis (for future multiple tokens usage will use [pallet_assets](https://paritytech.github.io/polkadot-sdk/master/pallet_assets/index.html) and [fungibles trait](https://paritytech.github.io/polkadot-sdk/master/frame_support/traits/tokens/fungibles/index.html)?) to get balances of given accounts and then sum the results, then return to executor, then executor return to `execute_query` api. Is this process right? And primitive types means u64 instead of bytes?
5. In the previous implementation (which is just simple arithmetic), I use [Polkadot Portal](https://polkadot.js.org/apps/#/explorer) to invoke state call with api name (XcqApi_execute_query) and polkavm program as `data`, which works well. However, if the arguments become `query` and `input`, I can't simply call it via Portal's UI, since I need combine two arguments into one bytes array. And it's part of functionals should be implemented by our SDK. So if I want to test the api, is there any recommend ways?
